### ISSUE TITLE
Half size classic editor

### ISSUE THREAD

**Issue by danavasilache** [Codeinwp/hestia#26]
Using the classic editor plugin with Hestia theme.  It seems the text doesn't go all way to the end of the textbox in Visual Mode.

In Visual Mode, the editor looks like this: https://prnt.sc/y6nrc3
But in Text Mode, it looks ok: https://prnt.sc/y6nt8k

Current version of WordPress: 5.6
Hestia - Version 3.0.8

**Comment by poonam279** [comment]
@cristian-ungureanu A Pro user is facing this issue. He hates block editor and wants to use classic editor only. Can we do something to fix this issue? 
HS: https://secure.helpscout.net/conversation/2087414407/347319?folderId=212385
