### ISSUE TITLE
Overflow texts only for Japanese on mobile

### ISSUE THREAD

**Issue by publishforpeace** [Codeinwp/hestia#29]
Hi, I have an issue with overflowing texts on mobile just for particular sections in my Japanese page. There is no issue with the English version. I made sure all the settings and formats are the same. Also, I initially copy&pasted the entire page from the English version, but after noticing the overflowing texts, I re-built those particular sections. But no luck.
You can see the overflowing texts here, if you see this on a mobile phone screen:
https://publishforpeace.com/ja

**Comment by selul** [comment]
hey, @publishforpeace, we don't have any particular style adapted for a different languages, the same rules apply to all of them. I'm not able to see the problematic section on your page so any help would be appreciated.

**Comment by publishforpeace** [comment]
Thanks. I managed to get a help from a friend to resolve it by putting some codes in the “additional CSS”.

Publish for Peace
***@***.***
https://publishforpeace.com
________________________________
