### ISSUE TITLE
General header issue on Hestia theme

### ISSUE THREAD

**Issue by nge90** [Codeinwp/hestia#31]
Hi, today I have seen this error on all the pages of my site:
Warning: is_file():  open_basedir restriction in effect. File(/src/Modules/Licenser.php) is not within the allowed path(s): (/web/htdocs/"url"/home/:/tmp:/dev/shm) in /web/htdocs/"url"/home/wp-content/themes/hestia/vendor/codeinwp/themeisle-sdk/load.php on line 27

I opened this file and at this row I have seen this:
if ( ! is_file( $themeisle_sdk_path . $themeisle_sdk_relative_licenser_path ) && is_file( $themeisle_sdk_max_path . $themeisle_sdk_relative_licenser_path ) ) {

This error appeared with the theme version: 3.0.16.
I updated to version 3.0.17 hoping to solve the issue but I receive the same error.
My Wordpress version is: 5.7.2
The site navigation is graphically corrupted in the homepage, and the Woocommerce widget has graphic errors.
Could you please help me?

**Comment by nge90** [comment]
To solve the problem I commented on the affected lines of code and the site is now working correctly

**Comment by selul** [comment]
@nge90 I think this was happening due to some corrupted install, due to the permission issues. Usually in such cases removing the theme entirely and re-installing it would help. 

Happy that

**Comment by nge90** [comment]
> 
> 
> @nge90 I think this was happening due to some corrupted install, due to the permission issues. Usually in such cases removing the theme entirely and re-installing it would help.

Thank you for your suggestion @selul

**Comment by zacekjg** [comment]
@selul 

I've also run into the problem described above. There is a code issue within the file specified in this thread, I've created a pull request that fixes it
