### ISSUE TITLE
The theme header disappears if the footer is created with the Elementor Pro builder

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/hestia#34]
The theme header disappears after creating the footer within the Elementor Pro builder and publishing the site.

**How to replicate the issue:**
1. Install and activate Elementor and Elementor Pro
2. Go to Templates -> Theme builder -> Footer, create a new footer and choose the condition to display it on the entire site
3. Publish the site
4. Observe that the header disappeared

Before creating the footer within the Elementor Pro builder:

<img width="945" alt="Capture" src="https://user-images.githubusercontent.com/86592341/130451952-d4062bf6-0112-4824-a726-5898f4f3c0ea.png">

After creating the footer within the Elementor Pro builder:

<img width="946" alt="Capture1" src="https://user-images.githubusercontent.com/86592341/130452070-d8f8da91-f466-46d6-9d6a-e7db891f25ac.PNG">
 
WordPress version: 5.8
Hestia version: 3.0.17

**Comment by cristian-ungureanu** [comment]
@MarinescuLucia only the PRO version is compatible with Elementor Header/Footer templates.
