### ISSUE TITLE
Can't edit HTML of front page

### ISSUE THREAD

**Issue by redimongo** [Codeinwp/hestia#35]
So the html for the front page is strange it has 
```
<div class="
		 big-title-slider-content text-center col-sm-8 col-sm-offset-2 		">
							<h1 class="hestia-title">Building Strong Business</h1>
										<span class="sub-title">Your One Stop Virtual Team</span>
										<div class="buttons">
					<a href="/contact" title="Learn More" class="btn btn-primary">Learn More</a>
									</div>
					</div>
```

But I need to remove 
```
col-sm-8 col-sm-offset-2 
```
and set it to 
```
col-sm-12
```

How is this done?

**Comment by selul** [comment]
Hi, 

This is not really an issue, for questions we recommend using the community-based forum on https://wordpress.org/support/theme/hestia/
Regarding your question, you could do this by using a child theme and change the markup according to your needs, more details on how to do that here https://developer.wordpress.org/themes/advanced-topics/child-themes/
