### ISSUE TITLE
Only the last product shows in shop page

### ISSUE THREAD

**Issue by giupeppe1984** [Codeinwp/hestia#36]
I have installed the Hestia lite theme on my test site. in the shop section I can see only one product, even if there are more than one. With other themes there aren't issue. For the e-commerce is woocommerce.
Hestia Version 3.0.19
WooCommerce Version 5.9.0

**Comment by cristian-ungureanu** [comment]
@giupeppe1984 I couldn't replicate this issue. Can you make a fresh site on [tastewp](https://tastewp.com/) where you replicate the issue and give us the credentials? Also, some screenshots or a video would help to identify the problem.

I'm closing this issue but feel free to comment here when you have more info. Thanks!

**Comment by giupeppe1984** [comment]
Hi team many thanks for your interest.
In my troubleshooting find that this plugin "*Gutentor - Gutenberg Blocks -
Page Builder for Gutenberg Editor*" generete the issue.
When active the shop page is behaving abnormally.
Show only one product ad when you click one more time on the Shop link all
the frontpage change the aspect and not work properly.
Best regards
Giuseppe De Leo

Il giorno ven 10 dic 2021 alle ore 15:42 cristian-ungureanu <
***@***.***> ha scritto:

**Comment by cristian-ungureanu** [comment]
Hi @giupeppe1984, thanks a lot for coming back with more details. We'll have it fixed in the next release, hopefully, tomorrow.

**Comment by giupeppe1984** [comment]
I'm happy to help you and your job in the comunity
