### ISSUE TITLE
CLS score bigger than recommended

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/hestia#42]
A user reported that the CLS score of the homepage is bigger than recommended, which is 0.1 or lower. For our demo site, [GTmetrix](https://gtmetrix.com/reports/demo.themeisle.com/qJowKZPE/) calculates the CLS score around 0.15, while [PageSpeed](https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.themeisle.com%2Fhestia%2F&form_factor=desktop) computes it around 0.25. However, Lighthouse shows the score at 0.025 on our demo site. Is there anything that could be improved about this?

Reported [here](https://wordpress.org/support/topic/layout-shift-on-page-load/).

Theme version: 3.0.21

**Comment by cristian-ungureanu** [comment]
@MarinescuLucia not much to do here. I think the pinpoint here would be the slider that resizes after the js script is loaded. You can recommend our user to disable the slider. An alternative would be to use custom layouts and for free users to rebuild the front page in Gutenberg.

I will close this ticket as there is nothing to do here. Feel free to reopen it if needed 🙏
