### ISSUE TITLE
Orbit Fox PlugIn Is breaking my Website withe Hestia Theme

### ISSUE THREAD

**Issue by ERALPHY** [Codeinwp/hestia#45]
I've disabled and re-activated all my plug ins and it's Orbit fix by Themeisle that's causing my events page not to load, i've gone through everything i've tried reactivation and refreshing everything i can but the bug won't go so at the moment i just have to keep it deactivated.

This is a big old issue because i need Orbit Fox for a main feature on my homepage

**Comment by cristian-ungureanu** [comment]
Hey @ERALPHY, we couldn't replicate this behavior. It would really help us if you could create a video of the issue. Can you share with us the list of your current plugins? Also, It would help to know the PHP version on your server.
Another thing you can try is to disable all modules of OrbitFox one by one, maybe there's a specific module that is causing the issue.
