### ISSUE TITLE
Contact section headings inconsistency

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/hestia#48]
The title of the Contact Us section is h2 and the description below it is h5, which may not be ideal for assistive technologies such as screen readers. A user suggested that changing the description from h5 to h3 would be an improvement in terms of accessibility.

![tempsnip](https://user-images.githubusercontent.com/86592341/186197390-a4bb3c46-f83f-4424-9b36-02729c394738.png)

Reported [here](https://wordpress.org/support/topic/contact-us-section-subtitle-should-be-h3-instead-of-h5/#post-15942597).

**Comment by girishpanchal30** [comment]
Hello @MarinescuLucia,

I reviewed the front page sections and found a similar structure in the below sections. Should I change user suggested structure for all sections?

1) What clients say
2) Meet our team
3) Products
4) Why our product is the best

cc @cristian-ungureanu

Thanks

**Comment by MarinescuLucia** [comment]
Hi @girishpanchal30,

Sorry for the delay, I had the week off.
Indeed it looks like this structure is repeated in multiple sections on the frontpage, including the Blog and Subscribe sections, besides those that you already mentioned. For accessibility reasons, I think we could consider changing this structure for all of them.

Thoughts @cristian-ungureanu?

**Comment by cristian-ungureanu** [comment]
@MarinescuLucia @girishpanchal30 this was the initial design as you can see here https://demos.creative-tim.com/material-kit-bs4/examples/landing-page.html. I think we can stick to it, not changing anything for now. The changes will produce lots of other visual issues.

@abaicus @selul ehat do you think?

**Comment by abaicus** [comment]
@MarinescuLucia Did a customer complain regarding this in a more elaborated manner? It's not optimal from an a11y perspective indeed, but it shouldn't affect screen readers flow unless headings are all over the place.

**Comment by MarinescuLucia** [comment]
@abaicus No, the user didn't provide other details. He just gave a heads up about this (mentioned only the contact section) not being ideal for accessibility [here](https://wordpress.org/support/topic/contact-us-section-subtitle-should-be-h3-instead-of-h5/).
