### ISSUE TITLE
Problem with Hestia and License fields of plugins

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/hestia#5]
Activation of hestia makes the license key fields disappear from the general settings page:

![image](https://user-images.githubusercontent.com/12953439/61102482-99d82700-a48b-11e9-81eb-ed04e707daaf.png)

cc @rodica-andronache

**Comment by rodica-andronache** [comment]
@contactashish13 I'm not able to replicate this. Is it Hestia or Hestia Pro? And is the license key already activated, and after activating the theme, it's just disappeared? For any of the 3 plugins?

**Comment by contactashish13** [comment]
@rodica-andronache its with both. @DanyCaissy tested with Hestia Pro and I with Hestia. 

Activation of the license key does not matter. The fields disappear before that happens. @DanyCaissy tried it as an end user and had to contact support for this to be resolved.
