### ISSUE TITLE
Unable to change the Big title section Button color 

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/hestia#51]
### Description

When updating Hestia to 3.0.25 users are unable to alter the color of the buttons on the big title section.

### Steps to replicate 

1. Go to customizer > Front page section > Big title section.
2. Try to change the color of the Big title section's button.
3. You will observe that nothing happens as the button is frozen.

### Reference 
A user reported here - https://wordpress.org/support/topic/cant-change-big-title-button-color
Screencast video URL - https://vertis.d.pr/v/hQupYq

### Technical details 
WordPress: 6.1.1
Hestia: 3.0.25

**Comment by kushh23** [comment]
The error in the console looks like this - https://vertis.d.pr/i/zRHeS6

**Comment by kushh23** [comment]
+1 : https://wordpress.org/support/topic/homepage-bug-with-hestia-3-0-25/

This user has faced the same issue with the latest update and also His Existing Big title section was breaked/disappeared after the update.

**Comment by girishpanchal30** [comment]
Hey @kushh23,

It seems related to #52, can you please check with this PR https://github.com/Codeinwp/hestia-pro/pull/2466?

Thanks

**Comment by cristian-ungureanu** [comment]
@girishpanchal30 I've tested it, and the button's color is changing now. While looking over it, I found this weird behavior, and I'm not sure if it's related or not with this issue.

https://vertis.d.pr/v/UvHdPG

Let me know what you think. Should I open another issue for it?

**Comment by girishpanchal30** [comment]
@cristian-ungureanu Fixed, Please check with this PR https://github.com/Codeinwp/hestia-pro/pull/2468 and let me know if you have found any issues.

Thanks

**Comment by cristian-ungureanu** [comment]
Thank you, @girishpanchal30!

@irinelenache, can you have a look over here and double-check if the initial issue and the one I've mentioned here https://vertis.d.pr/v/UvHdPG are fixed?

**Comment by irinelenache** [comment]
@cristian-ungureanu The mentioned issue is fixed on my end too 🚀
