### ISSUE TITLE
Version 3.0.25 allows multiple slide option in big title section

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/hestia#52]
The latest version of the theme allows you to create a slider in the free version, just like the Pro version. In previous versions, you could add only one slide in the big title section.

Screenshot with version 3.0.25 >> https://vertis.d.pr/i/cgCwDZ
Screenshot with version 3.0.24 >> https://vertis.d.pr/i/roVaoh

**Comment by girishpanchal30** [comment]
Hello @poonam279,

Reverted back to the old design, please check with the PR and let me know if you have any issues.

Thanks

**Comment by poonam279** [comment]
Hi @girishpanchal30, I have checked the PR and it worked.
