### ISSUE TITLE
The Orbit Fox notice appears anytime I get back to the panel

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/hestia#56]
Even if I pressed the "x" button and entered the Footer panel, for example, the Orbit Fox notice appears once I get back:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/86592992/230067473-8593a013-df58-4121-99ea-ae9bfff4a471.png">

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina,

I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/hestia-pro/pull/2512

Thanks
