### ISSUE TITLE
Menu icons change their appearance on the home page

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/hestia#64]
A user reported that the menu icons change their appearance when he switches to the home page.

I managed to replicate the issue, at least with the phone icon:
<img width="1680" alt="image" src="https://github.com/Codeinwp/hestia/assets/86592992/c0edb412-9bcd-4f78-b3a3-1ad1249c6ba5">
<img width="1680" alt="image" src="https://github.com/Codeinwp/hestia/assets/86592992/35e04d0a-b8c2-4e94-b440-d0647e9b6c56">
 

Ref: https://secure.helpscout.net/conversation/2445452303/395954?folderId=212390

**Comment by vytisbulkevicius** [comment]
related to https://github.com/Codeinwp/hestia-pro/issues/2563 we can work on updating version there, closing this one
