### ISSUE TITLE
X icon not displayed in Frontpage section

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/hestia#66]
A user reported that the X logo is not displayed on the homepage sections. I managed to replicate this issue:

1. Go to appearance > customize
2. Open the Frontpage Sections
3. Open the Team panel
4. Expand the accordion of a member and search for x/twitter
<img width="1680" alt="image" src="https://github.com/Codeinwp/hestia/assets/86592992/a06a4eb7-823a-4fdc-9a4d-bc41e5b0ac35">

Ref: https://wordpress.org/support/topic/hestia-3-1-1-issue-x-icon/#post-17347300

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina,

I've tested with the development branch and it seems visible from my end.
Ref: https://tinyurl.com/2of9xcvt

Could you please share your test instance details here?

Thanks

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, the issue is not valid anymore. Thanks for checking.
